version: "3.8"
services:
  postgres_db:
    image: postgres
    env_file: .env
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
