# Generated by Django 3.1.4 on 2020-12-05 04:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of plan', max_length=200, verbose_name='Name')),
                ('tar_included', models.BooleanField(verbose_name='Tar Included')),
                ('subscription', models.FloatField(help_text="It's the monthly subscription for the user", verbose_name='Subscription')),
                ('cycle', models.CharField(choices=[('DD', 'Daily'), ('WK', 'Weekly')], max_length=2, verbose_name='Cycle')),
                ('type', models.CharField(choices=[('BT', 'Bi-Time'), ('TT', 'Tri-Time'), ('ST', 'Simple')], max_length=2, verbose_name='Type')),
                ('offer_via', models.BooleanField(verbose_name='Offer IVA')),
                ('off_peak_price', models.FloatField(verbose_name='Off Peak Price')),
                ('peak_price', models.FloatField(verbose_name='Peak Price')),
                ('unit', models.CharField(choices=[('KWH', 'Kilometers/hour'), ('MIN', 'Minutes')], max_length=3, verbose_name='Unit')),
                ('valid', models.BooleanField(verbose_name='Valid')),
                ('publish', models.BooleanField(verbose_name='Publish')),
                ('vat', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Enter with a value greater than 1 and less than 100'), django.core.validators.MaxValueValidator(100, 'Enter with a value greater than 1 and less than 100')], verbose_name='Vat')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
