# Generated by Django 3.1.4 on 2020-12-05 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regularplan',
            old_name='offer_via',
            new_name='offer_iva',
        ),
    ]
