# Generated by Django 3.1.4 on 2020-12-05 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201205_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularplan',
            name='publish',
            field=models.BooleanField(help_text='Indicates if plan can be showed to everyone.', verbose_name='Publish'),
        ),
        migrations.AlterField(
            model_name='regularplan',
            name='vat',
            field=models.IntegerField(help_text='Choose a value from 1 to 100.', validators=[django.core.validators.MinValueValidator(1, 'Enter with a value greater than 1 and less than 100'), django.core.validators.MaxValueValidator(100, 'Enter with a value greater than 1 and less than 100')], verbose_name='Vat'),
        ),
    ]
